### ISSUE TITLE
BMO: Change security contexts to use capabilities

### ISSUE THREAD

**Issue by Xenwar** [metal3-io/baremetal-operator#384]
Currently, the security context of containers in BMO are set to use `privileged: true`. 
It might be better to limit the privileges using `capabilities`.

**Comment by stbenjam** [comment]
This is being fixed in https://github.com/metal3-io/baremetal-operator/pull/402

/kind cleanup

**Comment by Xenwar** [comment]
The issue #402 does not fix this issue. It set the security context correctly for the newly added container (ironic-endpoint-keepalived). All previous containers are not changed. They need to be fixed on a separate PR as it takes time to test each capability. Here is the current state. 
```
containers:
- name: ironic-endpoint-keepalived
    securityContext:
        capabilities:
        add: ["NET_ADMIN"]
- name: baremetal-operator
- name: ironic-dnsmasq
    securityContext:
    privileged: true
- name: mariadb
    securityContext:
    privileged: true
- name: ironic-httpd
    securityContext:
    privileged: true
- name: ironic
    securityContext:
    privileged: true
- name: ironic-inspector
    securityContext:
    privileged: true
initContainers:
- name: ironic-ipa-downloader
    securityContext:
    privileged: true

```

**Comment by maelk** [comment]
fixed by #416

**Comment by Xenwar** [comment]
fixed by #416, Therefore closing it.
